name: Compilar Mod Stardew Valley

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Compilar y exportar
      run: |
        PROJ=$(find . -name "*.csproj" | head -n 1)
        dotnet restore "$PROJ" --source "https://api.nuget.org/v3/index.json"
        dotnet build "$PROJ" --configuration Release
        mkdir -p ./output
        find . -type f \( -name "*.dll" -o -name "*.pdb" -o -name "manifest.json" \) -exec cp {} ./output/ \;

    - name: Subir Zip Compilado
      uses: actions/upload-artifact@v4
      with:
        name: GranjaModernaMod-Compilado
        path: ./output/
