name: Compilar Mod Stardew Valley

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restaurar dependencias
      run: find . -name "*.csproj" -exec dotnet restore {} --source "https://api.nuget.org/v3/index.json" \;

    - name: Compilar
      run: find . -name "*.csproj" -exec dotnet build {} --configuration Release --output ./output \;

    - name: Subir Zip Compilado
      uses: actions/upload-artifact@v4
      with:
        name: GranjaModernaMod-Compilado
        path: ./output/
