name: Compilar Mod Stardew Valley

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Localizar proyecto
      run: |
        PROJ=$(find . -maxdepth 2 -iname "*.csproj" | head -n 1)
        echo "PROJ_PATH=$PROJ" >> $GITHUB_ENV
        echo "Archivo detectado: $PROJ"

    - name: Restaurar dependencias
      run: dotnet restore "$PROJ_PATH" --source "https://api.nuget.org/v3/index.json"

    - name: Compilar
      run: dotnet build "$PROJ_PATH" --configuration Release

    - name: Preparar carpeta de salida
      run: |
        mkdir -p ./output
        find . -type f \( -iname "*.dll" -o -iname "*.pdb" -o -iname "manifest.json" \) -exec cp {} ./output/ \;

    - name: Subir Zip Compilado
      uses: actions/upload-artifact@v4
      with:
        name: GranjaModernaMod-Compilado
        path: ./output/
